import type { Metadata } from "next";
import "../globals.css";
import Menu from "@/ui/components/template/Menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <div className="flex w-screen h-screen">
        <Menu/>
        <div className="flex-1 relative overflow-hidden">
          <div className="w-full h-full overflow-auto">
            {children}
          </div>
        </div>
        </div>
      </body>
    </html>
  );
}
